# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170415_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreradecine',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
