# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_carreradecine_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandeestudios',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='plandeestudios',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='plandeestudios',
            name='last_name',
        ),
    ]
