# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170415_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandeestudios',
            options={'ordering': ['order'], 'verbose_name': 'Plan de estudios', 'verbose_name_plural': 'Planes de estudio'},
        ),
        migrations.AddField(
            model_name='plandeestudios',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
