# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170416_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandeestudios',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
