# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_carreradecine_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursostalleres',
            options={'ordering': ['order'], 'verbose_name': 'CursoTaller', 'verbose_name_plural': 'CursosTalleres'},
        ),
        migrations.AddField(
            model_name='cursostalleres',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cursostalleres',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursostalleres',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
