# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20170416_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temario',
            options={'ordering': ['order'], 'verbose_name': 'Temario', 'verbose_name_plural': 'Temarios'},
        ),
        migrations.AddField(
            model_name='temario',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='temario',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
