# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:37
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20170416_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temario',
            name='curso',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.CursosTalleres'),
        ),
    ]
