# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:46
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20170416_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursostalleres',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
