# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_productora_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productora',
            name='second_description',
        ),
    ]
