# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_operasprimas_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cortometrajes',
            options={'ordering': ['order'], 'verbose_name': 'Cortometraje', 'verbose_name_plural': 'Cortometrajes'},
        ),
        migrations.AlterModelOptions(
            name='operasprimasentries',
            options={'ordering': ['order'], 'verbose_name': 'Opera Prima', 'verbose_name_plural': 'Operas Primas'},
        ),
        migrations.RemoveField(
            model_name='operasprimas',
            name='second_description',
        ),
        migrations.AddField(
            model_name='cortometrajes',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cortometrajes',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operasprimasentries',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='operasprimasentries',
            name='slug',
            field=models.CharField(default=1, editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
