# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20170417_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operasprimasentries',
            options={'ordering': ['order'], 'verbose_name': 'Opera Prima Video', 'verbose_name_plural': 'Operas Primas Videos'},
        ),
    ]
