# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 04:37
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20170417_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmografia',
            options={'ordering': ['order'], 'verbose_name': 'Entrada de filmografia', 'verbose_name_plural': 'Entradas de filmografia'},
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='avatart',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='filmografia',
            name='video',
        ),
        migrations.AddField(
            model_name='filmografia',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='filmografia',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=cms.models.upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmografia',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
