# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20170417_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmografia',
            old_name='poster',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='avatar',
            new_name='image',
        ),
    ]
