# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20170417_0445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['order'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AddField(
            model_name='personal',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='personal_type',
            field=models.CharField(choices=[('DIR', 'Directiva'), ('DOC', 'Plantilla Docente')], default='DOC', max_length=3),
        ),
        migrations.AddField(
            model_name='personal',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
