# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_messageshome_mosaicoshome'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageshome',
            name='page_link',
            field=models.CharField(choices=[('CAR', 'carrera de cine'), ('CUR', 'cursos / talleres'), ('OPE', 'Óperas primas / cortometrajes'), ('PRO', 'productora / películas'), ('PLA', 'plantilla docente'), ('HOM', 'home')], default='DOC', max_length=3),
        ),
    ]
