# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 21:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_boutique_contacto_guiaalumnomessages_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreradecine',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='carreradecine',
            name='message_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='carreradecine',
            name='second_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
