# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 21:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_cktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cktest',
            name='file',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2017, 4, 18, 21, 56, 38, 104979, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
