# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:30
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_cktest_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image_frente',
            field=models.FileField(default=django.utils.timezone.now, upload_to=cms.models.upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='image_plataforma',
            field=models.FileField(default='1', upload_to=cms.models.upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='link_frente',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='link_plataforma',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
    ]
