# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_auto_20170419_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='link_frente',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='link_plataforma',
            field=models.URLField(blank=True, null=True),
        ),
    ]
