# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:31
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_auto_20170419_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortometrajes',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=cms.models.upload_to),
            preserve_default=False,
        ),
    ]
