# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_auto_20170421_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('vimeo', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
