# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-03 16:09
from __future__ import unicode_literals

import cms.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='description',
            field=models.CharField(default=datetime.datetime(2017, 5, 3, 16, 9, 9, 694162, tzinfo=utc), max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='preview',
            field=models.ImageField(default='preview', upload_to=cms.models.upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='title',
            field=models.CharField(default='title', max_length=50),
            preserve_default=False,
        ),
    ]
