# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_auto_20170503_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
