# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_auto_20170503_2253'),
        ('cms', '0037_auto_20170503_1616'),
    ]

    operations = [
    ]
