# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_cktest_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
