# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-01 17:11
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_auto_20170517_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='operasprimasentries',
            name='image',
            field=models.ImageField(default=1, upload_to=cms.models.upload_to),
            preserve_default=False,
        ),
    ]
