# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_operasprimasentries_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='youtube',
            field=models.URLField(default='youtube'),
            preserve_default=False,
        ),
    ]
