# Generated by Django 2.1.4 on 2019-01-18 20:41

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.FileField(upload_to=cms.models.upload_to),
        ),
    ]
